// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDakrsBkErpwpX5Ezrr3y9aLJ7MuLw9kEE',
    appId: '1:1093468809941:web:9814baea95fd2a5804105c',
    messagingSenderId: '1093468809941',
    projectId: 'mycart-c745d',
    authDomain: 'mycart-c745d.firebaseapp.com',
    storageBucket: 'mycart-c745d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfSk0SQE4UT0EecTF0A_mYeCgcQEdIS6Q',
    appId: '1:1093468809941:android:ca7c7d659bf2a00f04105c',
    messagingSenderId: '1093468809941',
    projectId: 'mycart-c745d',
    storageBucket: 'mycart-c745d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBW-L0U1HUIWqeftrlbJY8lTVw4KiW-3Q',
    appId: '1:1093468809941:ios:005f653b3c97230004105c',
    messagingSenderId: '1093468809941',
    projectId: 'mycart-c745d',
    storageBucket: 'mycart-c745d.appspot.com',
    iosClientId: '1093468809941-rqp56jijr3965u49r8uhld86o88gvr2f.apps.googleusercontent.com',
    iosBundleId: 'com.agromother.mycart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBW-L0U1HUIWqeftrlbJY8lTVw4KiW-3Q',
    appId: '1:1093468809941:ios:005f653b3c97230004105c',
    messagingSenderId: '1093468809941',
    projectId: 'mycart-c745d',
    storageBucket: 'mycart-c745d.appspot.com',
    iosClientId: '1093468809941-rqp56jijr3965u49r8uhld86o88gvr2f.apps.googleusercontent.com',
    iosBundleId: 'com.agromother.mycart',
  );
}
